#!/bin/sh
# this is a copy of /etc/X11/xinit/xinitrc
# my stuff is below that
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
# --------------------------
#xrdb ~/.Xresources
setxkbmap hu

# xbindskeyrc is wm agnostic, but I prefer flux keys
#xbindkeys &

# problems galore, do NOT enable
#compton -b

dropboxd &
exec startfluxbox
